name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t skakarla1/node-express-app:latest .

      # Run the Docker container in the background
      - name: Run Docker container
        run: docker run -d -p 80:80 --name node-express-app skakarla1/node-express-app:latest

      # Wait for container to start
      - name: Wait for container to start
        run: sleep 10

      # Verify application functionality
      - name: Verify Application Functionality
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      # Stop and remove the Docker container
      - name: Stop and Remove Docker container
        run: docker stop node-express-app && docker rm node-express-app
        
      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push skakarla1/node-express-app:latest