name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/liatroclouddeployment/cloud-run-source-deploy/node-express-app:latest .

      # Run the Docker container in the background 
      - name: Run Docker container
        run: docker run -d -p 80:80 --name node-express-app us-central1-docker.pkg.dev/liatroclouddeployment/cloud-run-source-deploy/node-express-app:latest

      # Wait for container to start 
      - name: Wait for container to start
        run: sleep 10

      # Verify application functionality
      - name: Verify Application Functionality
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      # Stop and remove the Docker container 
      - name: Stop and Remove Docker container
        run: docker stop node-express-app && docker rm node-express-app
    
      # Push Docker image to Google Container Registry
      - name: Push Docker image to Google Artifact Registry
        run: docker push us-central1-docker.pkg.dev/liatroclouddeployment/cloud-run-source-deploy/node-express-app:latest

      # Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
         gcloud run deploy node-express-app \
           --image us-central1-docker.pkg.dev/liatroclouddeployment/cloud-run-source-deploy/node-express-app:latest \
           --platform managed \
           --region us-central1 \
           --allow-unauthenticated