name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-express-app:latest .

      # Verify application functionality
      - name: Verify Application Functionality
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
        
      # Push Docker image to Google Container Registry
      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_SA_KEY }}/node-express-app:latest

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_SA_KEY }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy node-express-app \
            --image gcr.io/${{ secrets.GCP_SA_KEY }}/node-express-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated